
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Mar 06 17:14:09 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 44;
  public static final int CONST = 8;
  public static final int GE = 29;
  public static final int NUMCONST = 50;
  public static final int CASE = 20;
  public static final int LPAREN = 42;
  public static final int SEMI = 39;
  public static final int CONTINUE = 16;
  public static final int FOR = 17;
  public static final int MINUS = 22;
  public static final int RPAREN = 43;
  public static final int OROR = 33;
  public static final int LT = 30;
  public static final int COMMA = 40;
  public static final int CLASS = 5;
  public static final int INC = 35;
  public static final int DIV = 24;
  public static final int ANDAND = 32;
  public static final int PLUS = 21;
  public static final int ASSIGN = 34;
  public static final int IF = 9;
  public static final int DOT = 41;
  public static final int LE = 31;
  public static final int ABSTRACT = 6;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int RBRACKET = 45;
  public static final int NEW = 10;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 23;
  public static final int EQEQ = 26;
  public static final int MOD = 25;
  public static final int NEQ = 27;
  public static final int IDENT = 49;
  public static final int BREAK = 3;
  public static final int VOID = 14;
  public static final int SWITCH = 19;
  public static final int COLON = 38;
  public static final int LBRACE = 46;
  public static final int ELSE = 7;
  public static final int ENUM = 4;
  public static final int READ = 12;
  public static final int CHARCONST = 51;
  public static final int RBRACE = 47;
  public static final int BOOLCONST = 48;
  public static final int EXTENDS = 15;
  public static final int QUESTION = 37;
  public static final int DEC = 36;
  public static final int GT = 28;
  public static final int PRINT = 11;
  public static final int LENGTH = 18;
}

